name: CI/CD for MinilibX

on:  # Добавьте эту секцию
  push:
    branches: [ main ]  # Запускать при push в ветку main
  pull_request:         # Или при создании pull request
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y gcc make xorg libxext-dev libbsd-dev

      - name: Clone MinilibX
        run: git clone https://github.com/42Paris/minilibx-linux.git mlx

      - name: Build MinilibX
        run: |
          cd mlx
          make

      - name: Run tests
        run: make vbtest
